language: php
php:
  - "5.4"
  - "5.3"

before_script:
  - pear install pear/PHP_CodeSniffer
  - pecl install oauth
  - phpenv rehash
  - php bin/composer install

script:
  - phpcs --standard=PSR2 src/Bendihossan/Phitter
